site_name: Mixing Station Docs
theme:
  name: 'material'

plugins:
  - pdf-export

nav:
  - Home: index.md
  - Versions & Features: feature-list.md
  - Getting started: 
    - General: getting-started.md
    - UI controls: ui-controls.md
    - Sends on faders: sends-on-faders.md
    - Layers: layers.md
    - Settings: settings.md
    - App settings: app-settings.md
    - Global settings: global-settings.md
  - Advanced:
    - IDCAs: layer-idcas.md
    - Mix copy: mix-copy.md
    - Re-Gain: re-gain.md
    - Custom layouts: custom-layouts.md
    - USB Midi: usb-midi.md
    - Actions: custom-actions.md
    - Feedback detection: feedback-detection.md
  - Beta program: beta.md
  - XAir:
      Bus password: xair/bus-password.md
  - XM32:
      Channel move: xm32/channel-move.md
      Bus password: xm32/bus-password.md
      X32-Mix lag: xm32/network-compare.md
      Samsung & Android 6: xm32/samsung-android6.md
  - Souncraft:
      Si: soundcraft/si-performer.md
      HiQNet: soundcraft/hiqnet.md

  - Known issues: known-issues.md
  - Privacy policy: https://dev-core.org/dsgvo
