site_name: Mixing Station Docs
theme:
  name: 'material'

plugins:
  - pdf-export:
      media_type: print
      combined: true
  
nav:
  - Home: index.md
  - Versions & Features: feature-list.md
  - Platforms:
    - PC: platforms/pc.md
    - Android: platforms/android.md
    - iOS: platforms/ios.md
  - Getting started: 
    - General: getting-started.md
    - UI controls: ui-controls.md
    - Sends on faders: sends-on-faders.md
    - Settings: 
      - Overview: settings/overview.md
      - Global settings: settings/global.md
      - Model settings: settings/console-model.md
      - User / Session settings: settings/user_session.md
    - Layers: layers.md
    - Channel strip: settings/channel-strip.md
  - Advanced:
    - IDCAs: layer-idcas.md
    - Mix copy: mix-copy.md
    - Re-Gain: re-gain.md
    - Custom layouts: custom-layouts.md
    - Midi: midi.md
    - Actions: custom-actions.md
    - Auto EQ: auto-eq.md
    - Feedback detection: feedback-detection.md
    - Autostart: autostart.md
  - Beta program: beta.md
  - APIs: integrations/apis.md
  - WING:
      General: wing/general.md
  - XAir:
      Bus password: xair/bus-password.md
  - XM32:
      Channel move: xm32/channel-move.md
      Bus password: xm32/bus-password.md
      X32-Mix lag: xm32/network-compare.md
      Samsung & Android 6: xm32/samsung-android6.md
  - Soundcraft:
      Si: soundcraft/si-performer.md
      HiQNet: soundcraft/hiqnet.md
  - Allen & Heath:
      General: ah/general.md

  - Known issues: known-issues.md
  - Privacy policy: https://dev-core.org/dsgvo


markdown_extensions:
  - attr_list