site_name: Mixing Station Docs
theme:
  name: 'material'
  
nav:
  - Home: index.md
  - Getting started: 
    - General: getting-started.md
    - UI controls: ui-controls.md
    - Sends on faders: sends-on-faders.md
    - Layers: layers.md
    - App settings: app-settings.md
  - Advanced:
    - IDCAs: layer-idcas.md
    - Mix copy: mix-copy.md
    - USB Midi: usb-midi.md
  - Beta program: beta.md
  - XM32:
      Channel move: xm32/channel-move.md
      X32-Mix lag: xm32/network-compare.md

